name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI, Kubectl, and Helm
        run: |
          sudo apt-get update && sudo apt-get install -y curl unzip
          
          # Update AWS CLI if already installed
          if aws --version &>/dev/null; then
            echo "AWS CLI already installed, updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "Installing AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi
          
          aws --version


      - name: Get Commit ID
        run: echo "COMMIT_ID=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Login to AWS ECR
        run: |
          echo "Logging in to AWS ECR..."
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t frontend:${{ env.COMMIT_ID }} .
          docker tag frontend:${{ env.COMMIT_ID }} ${{ secrets.ECR_REPO }}:${{ env.COMMIT_ID }}

      - name: Push Docker image to ECR
        run: |
          echo "Pushing Docker image to ECR..."
          docker push ${{ secrets.ECR_REPO }}:${{ env.COMMIT_ID }}

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI, Kubectl, and Helm
        run: |
          sudo apt-get update && sudo apt-get install -y curl unzip
          
          # Install AWS CLI
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version
          
          # Install Kubectl
          curl -sLO "https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          kubectl version --client
          
          # Install Helm
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Get Commit ID
        run: echo "COMMIT_ID=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Configure AWS CLI for EKS
        run: |
          echo "Configuring AWS CLI for EKS..."
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}

      - name: Deploy with Helm
        run: |
          echo "Deploying with Helm..."
          helm upgrade --install ${{ secrets.HELM_RELEASE }} ./${{ secrets.HELM_REPO_PATH }} \
            -f ${{ secrets.HELM_REPO_PATH }}/values.yaml \
            --set image.frontend.tag=${{ env.COMMIT_ID }} \
            --description "Git Commit ${{ env.COMMIT_ID }}"
          
          cat ./${{ secrets.HELM_REPO_PATH }}/values.yaml

      - name: Restart Frontend Deployment
        run: |
          echo "Restarting Frontend Deployment..."
          kubectl rollout restart deployment ${{ secrets.FRONTEND_DEPLOYMENT_NAME }}
